apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: okra-home-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      name: okra-home
  template:
    metadata:
      labels:
        name: okra-home
    spec:
      containers:
      - name: git-sync
        image: mirrorgooglecontainers/git-sync:v3.0.1
        volumeMounts:
        - name: home
          mountPath: /home
        env:
        - name: GIT_SYNC_REPO
          value: https://gitee.com/nuptaxin/okra-home
        - name: GIT_SYNC_ROOT
          value: /home
        - name: GIT_SYNC_DEST
          value: okra-home
      - name: docsify
        image: nuptaxin/docsify-docker:v1.0.0
        workingDir: /home/okra-home/docs
        volumeMounts:
        - name: home
          mountPath: /home
      volumes:
      - name: home
        emptyDir: {}
